apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-92bjs
kind: ServiceAccount
metadata:
  name: default
  namespace: file-uploader
secrets:
- name: default-token-6m6f6
- name: default-dockercfg-92bjs
