apiVersion: v1
imagePullSecrets:
- name: pipeline-dockercfg-2xbg7
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: file-uploader
secrets:
- name: pipeline-dockercfg-2xbg7
- name: pipeline-token-hcnwv
